// Copyright 2026 Zyvor AI Labs · https://zyvor.dev
// SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0

/** One-line descriptions shown under each item in the top-bar flyouts (Netra-style mega panels). */
const BLURBS: Record<string, string> = {
  '/platform': 'Fleet health at a glance',
  '/platform/workloads': 'Everything running on the fleet',
  '/platform/applications': 'Apps and the VMs behind them',
  '/platform/vms': 'Inventory, power, migrate',
  '/k8s/workloads': 'Pods, deployments, services',
  '/vms': 'Libvirt guests on this host',
  '/create': 'Image, size, network, boot',
  '/containers': 'Podman and Docker containers',
  '/platform/templates': 'Golden images and templates',
  '/platform/fleet-snapshots': 'Snapshots across hosts',
  '/platform/blueprints': 'Repeatable environments',
  '/platform/infrastructure': 'Hosts, storage, networks',
  '/platform/datacenter': 'Sites, racks and hosts',
  '/platform/hosts': 'Hypervisors and their health',
  '/platform/storage': 'Pools, volumes, disk health',
  '/platform/networks': 'Bridges, VLANs, firewalls',
  '/platform/reports': 'Capacity and usage',
  '/platform/gpu': 'GPU inventory and passthrough',
  '/platform/content': 'ISOs and disk images',
  '/platform/cloud-init': 'Author cloud-init configs',
  '/networks': 'Libvirt networks on this host',
  '/storage': 'Libvirt storage pools',
  '/platform/operations': 'Monitoring, events, backups',
  '/platform/activity': 'Live fleet activity',
  '/platform/events': 'Audit and event stream',
  '/platform/backups': 'Backups and restore points',
  '/platform/maintenance': 'Upgrades and maintenance windows',
  '/platform/tasks': 'Running and recent tasks',
  '/platform/notifications': 'Active alerts',
  '/platform/alert-rules': 'When to notify, and who',
  '/platform/scheduled-jobs': 'Recurring jobs',
  '/platform/migration': 'Move VMs between hosts',
  '/platform/network-canvas': 'Visual network map',
  '/platform/placement': 'Disaster recovery placement',
  '/platform/topology': 'How everything connects',
  '/platform/observability': 'Metrics, logs and traces',
  '/platform/recommendations': 'Suggestions from Zyra',
  '/platform/soc': 'Alerts and detections',
  '/platform/zeus/security': 'Fleet security posture',
  '/platform/zeus/security/firewall': 'Host firewall profiles',
  '/platform/zeus/security/ports': 'Exposed ports and services',
  '/platform/zeus/security/services': 'Allowed applications',
  '/platform/zeus/security/activity': 'Blocked and allowed traffic',
  '/platform/zeus/security/compliance': 'Policy and drift checks',
  '/platform/zeus/security/k8s': 'Kubernetes network policy',
  '/platform/zeus/security/cloud': 'Cloud security groups',
  '/platform/zeus/security/connectivity': 'Who talks to whom',
  '/platform/zyra/security/hunt': 'Search for threats',
  '/platform/zyra/security/enforcement': 'Kernel-level deny rules',
  '/platform/zyra/security/native-bpf': 'Native eBPF datapath',
  '/platform/zyra/security/network-policies': 'Which VM talks to which',
  '/platform/administration': 'Users, projects, policy',
  '/platform/users': 'Accounts and groups',
  '/platform/projects': 'Group and isolate workloads',
  '/platform/policy': 'Fleet-wide rules',
  '/platform/settings': 'Preferences and integrations',
  '/platform/enterprise': 'Enterprise features',
  '/platform/api-keys': 'Tokens for automation',
  '/platform/webhooks': 'Send events elsewhere',
  '/fleet-cloud': 'Native cloud-style compute',
  '/platform/zyra': 'AI operations assistant',
  '/platform/zyra/configure': 'Models, memory and limits',
  '/platform/ai-providers': 'LLM providers and routing',
  '/platform/enroll': 'Add a hypervisor host',
  '/platform/upgrade': 'Version and upgrade matrix',
  '/k8s': 'Cluster overview',
}

export function navBlurb(to: string): string | undefined {
  return BLURBS[to.split('?')[0]]
}
