#!/usr/bin/env bash
# Wire Machina to an OpenStack cloud (Packstack keystonerc, openrc, or existing clouds.yaml).
#
# Usage (on the hypervisor host, as root):
#   sudo ./scripts/openstack-wire-cloud.sh
#   sudo ./scripts/openstack-wire-cloud.sh /root/keystonerc_admin packstack
#
# Creates:
#   /etc/openstack/clouds.yaml
#   /etc/machina/openstackrc  (sourced by machina-daemon via EnvironmentFile)
# Updates [openstack] in /etc/machina/config.toml when present.
set -euo pipefail

RC_FILE="${1:-/root/keystonerc_admin}"
CLOUD_NAME="${2:-packstack}"
CLOUDS_YAML="/etc/openstack/clouds.yaml"
OPENRC_OUT="/etc/machina/openstackrc"
CONFIG="/etc/machina/config.toml"

if [[ ! -f "$RC_FILE" ]]; then
  echo "Missing RC file: $RC_FILE" >&2
  echo "Usage: $0 [keystonerc_admin] [cloud_name]" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$RC_FILE"

: "${OS_AUTH_URL:?OS_AUTH_URL not set in $RC_FILE}"
: "${OS_USERNAME:?OS_USERNAME not set}"
: "${OS_PASSWORD:?OS_PASSWORD not set}"

PROJECT="${OS_PROJECT_NAME:-${OS_TENANT_NAME:-admin}}"
USER_DOMAIN="${OS_USER_DOMAIN_NAME:-Default}"
PROJECT_DOMAIN="${OS_PROJECT_DOMAIN_NAME:-Default}"
REGION="${OS_REGION_NAME:-RegionOne}"
INTERFACE="${OS_INTERFACE:-public}"

mkdir -p /etc/openstack /etc/machina

# Pre-create with restrictive perms: a plain `>` redirect to a not-yet-existing
# file creates it with the process umask (often 644, world-readable), so the
# OS_PASSWORD written below would briefly sit in a world-readable file until
# the `chmod 600` further down ran.
install -m 600 /dev/null "$CLOUDS_YAML"
cat >"$CLOUDS_YAML" <<EOF
# Generated by machina scripts/openstack-wire-cloud.sh
clouds:
  ${CLOUD_NAME}:
    auth:
      auth_url: ${OS_AUTH_URL}
      username: ${OS_USERNAME}
      password: ${OS_PASSWORD}
      project_name: ${PROJECT}
      user_domain_name: ${USER_DOMAIN}
      project_domain_name: ${PROJECT_DOMAIN}
    region_name: ${REGION}
    interface: ${INTERFACE}
EOF
chmod 600 "$CLOUDS_YAML"

# systemd EnvironmentFile: KEY=value only (no export / PS1). Always write from sourced env
# so indented Packstack keystonerc files work reliably.
# Same pre-create-with-600 reasoning as $CLOUDS_YAML above — OS_PASSWORD is written below.
install -m 600 /dev/null "$OPENRC_OUT"
{
  echo "OS_AUTH_URL=${OS_AUTH_URL}"
  echo "OS_USERNAME=${OS_USERNAME}"
  echo "OS_PASSWORD=${OS_PASSWORD}"
  echo "OS_PROJECT_NAME=${PROJECT}"
  echo "OS_USER_DOMAIN_NAME=${USER_DOMAIN}"
  echo "OS_PROJECT_DOMAIN_NAME=${PROJECT_DOMAIN}"
  echo "OS_REGION_NAME=${REGION}"
  echo "OS_IDENTITY_API_VERSION=3"
} >"$OPENRC_OUT"
chmod 600 "$OPENRC_OUT"

if [[ -f "$CONFIG" ]]; then
  if grep -q '^\[openstack\]' "$CONFIG"; then
  # CLOUD_NAME/REGION/PROJECT come from the sourced keystonerc (2nd CLI arg / RC file
  # content — not fully trusted) and were previously interpolated straight into this
  # Python source via a shell heredoc: a value containing `"""` or a newline could break
  # out of the string literal and inject arbitrary Python, run as root. Pass them as
  # argv instead so they're always plain data, never source code.
  python3 - "$CONFIG" "$CLOUD_NAME" "$CLOUDS_YAML" "$REGION" "$PROJECT" <<'PY'
from pathlib import Path
import re, sys
cfg_path, cloud_name, clouds_yaml, region, project = sys.argv[1:6]
cfg = Path(cfg_path).read_text()
block = (
    "[openstack]\n"
    "enabled = true\n"
    f"cloud_name = {cloud_name!r}\n"
    f"clouds_yaml_path = {clouds_yaml!r}\n"
    "connect_timeout_secs = 30\n"
    "use_env_auth = false\n"
    "upload_enabled = true\n"
    "upload_timeout_secs = 3600\n"
    f"default_os_cloud = {cloud_name!r}\n"
    "default_boot_instance = false\n"
    "default_flavor = \"m1.tiny\"\n"
    "default_network = \"private\"\n"
    f"region = {region!r}\n"
    f"project_name = {project!r}\n"
)
if re.search(r'^\[openstack\]', cfg, re.M):
    cfg = re.sub(r'(?ms)^\[openstack\].*?(?=^\[|\Z)', block + "\n", cfg)
else:
    cfg = cfg.rstrip() + "\n\n" + block + "\n"
Path(cfg_path).write_text(cfg)
PY
  else
    cat >>"$CONFIG" <<EOF

[openstack]
enabled = true
cloud_name = "${CLOUD_NAME}"
clouds_yaml_path = "${CLOUDS_YAML}"
connect_timeout_secs = 30
use_env_auth = false
upload_enabled = true
upload_timeout_secs = 3600
default_os_cloud = "${CLOUD_NAME}"
default_boot_instance = false
default_flavor = "m1.tiny"
default_network = "private"
region = "${REGION}"
project_name = "${PROJECT}"
EOF
  fi
fi

if [[ -f /etc/default/machina-daemon ]]; then
  if ! grep -q openstackrc /etc/default/machina-daemon 2>/dev/null; then
    echo "# OpenStack credentials for machina-daemon (optional; clouds.yaml is primary)" >>/etc/default/machina-daemon
  fi
fi

systemctl daemon-reload
systemctl restart machina-daemon 2>/dev/null || true

echo "Wrote ${CLOUDS_YAML} (cloud: ${CLOUD_NAME})"
echo "Wrote ${OPENRC_OUT}"
echo "Restarted machina-daemon"
echo "Test: curl -sk https://127.0.0.1:5092/api/v1/openstack/status (after login)"
